=== nhauser/cdma/dictionaries/trunk/plugin_config_file.dtd
<?xml version="1.0" encoding="UTF8"?>
<!ELEMENT plugin-config  (global? | dataset_model*)>
<!ATTLIST plugin-config 
    name CDATA #REQUIRED
>

<!-- 
==========================
global
========================== 
-->
<!ELEMENT global (java? | cpp?)>
<!ELEMENT java (set*)>
<!ELEMENT cpp (set*)>
<!ELEMENT set EMPTY>
<!ATTLIST set 
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!--
==========================
dataset_model
========================== 
-->
<!ELEMENT dataset-model (criteria? , parameters? , plugin? )>
<!ATTLIST dataset-model 
    name CDATA #REQUIRED
>
    
<!--
==========================
plugin
========================== 
--> 
<!ELEMENT plugin ( java? | cpp? )>


<!--
==========================
criteria
========================== 
-->
<!ELEMENT criteria (if*)>
<!ELEMENT if EMPTY>
<!ATTLIST if 
    target CDATA #REQUIRED
    exist ( true | false ) #IMPLIED
    equal CDATA #IMPLIED
    not_equal CDATA #IMPLIED
>


<!--
==========================
parameters
========================== 
-->
<!ELEMENT parameters (parameter*)>
<!ELEMENT parameter (value?)>
<!ATTLIST parameter
    name CDATA #REQUIRED
    value CDATA #IMPLIED
>

<!ELEMENT value EMPTY>
<!ATTLIST value 
    type ( exist | name | value | constant | equal ) #REQUIRED
    target CDATA #IMPLIED
    test ( true | false ) #IMPLIED
    constant CDATA #IMPLIED
>

=== nhauser/cdma/dictionaries/trunk/mappings/MamboSoleil/cdma_mambosoleil_config.xml
<?xml version="1.0" encoding="UTF8"?>
<!DOCTYPE plugin-config SYSTEM "../../dtd/plugin_config_file.dtd">
<plugin-config name="SOLEIL's Mambo plug-in configuration file">


<!-- ============================================
==  CONFIG 1: detection by file information    ==
============================================= -->
  <dataset-model name="fully_defined_conf">
    <plugin>
      <java>
        <set name="HDB_RAC" value=""/>
        <set name="HDB_DRIVER" value=""/>
        <set name="HDB_HOST" value=""/>
        <set name="HDB_NAME" value=""/>
        <set name="HDB_PORT" value=""/>
        <set name="HDB_SCHEMA" value=""/>
        <!--
        <set name="HDB_USER" value=""/>
        <set name="HDB_PASSWORD" value=""/>
        -->
        <set name="TDB_RAC" value=""/>
        <set name="TDB_DRIVER" value=""/>
        <set name="TDB_HOST" value=""/>
        <set name="TDB_NAME" value=""/>
        <set name="TDB_PORT" value=""/>
        <set name="TDB_SCHEMA" value=""/>
        <!--
        <set name="TDB_USER" value=""/>
        <set name="TDB_PASSWORD" value=""/>
        -->
      </java>
    </plugin>
  </dataset-model>
</plugin-config>

=== nhauser/cdma/dictionaries/trunk/mappings/MamboSoleil/degrad_cdma_mambosoleil_config.xml
<?xml version="1.0" encoding="UTF8"?>
<!DOCTYPE plugin-config SYSTEM "../../dtd/plugin_config_file.dtd">
<plugin-config name="SOLEIL's Mambo plug-in configuration file">


<!-- ============================================
==  CONFIG 1: detection by file information    ==
============================================= -->
  <dataset-model name="fully_defined_conf">
    <plugin>
      <java>
        <set name="HDB_RAC" value="false"/>
        <set name="HDB_DRIVER" value="jdbc:oracle:thin"/>
        <set name="HDB_HOST" value="(DESCRIPTION = (ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS = (PROTOCOL = TCP)(HOST = calliope-vip.rcm) (PORT = 1521)) (ADDRESS = (PROTOCOL = TCP)(HOST = euterpe-vip.rcm)(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME = HDB)))"/>
        <set name="HDB_NAME" value="DEGRAD"/>
        <set name="HDB_PORT" value="1521"/>
        <set name="HDB_SCHEMA" value="hdb"/>
        <!--
        <set name="HDB_USER" value=""/>
        <set name="HDB_PASSWORD" value=""/>
        -->
        <set name="TDB_RAC" value="false"/>
        <set name="TDB_DRIVER" value=""/>
        <set name="TDB_HOST" value=""/>
        <set name="TDB_NAME" value=""/>
        <set name="TDB_PORT" value=""/>
        <set name="TDB_SCHEMA" value=""/>
        <!--
        <set name="TDB_USER" value=""/>
        <set name="TDB_PASSWORD" value=""/>
        -->
      </java>
    </plugin>
  </dataset-model>
</plugin-config>

=== nhauser/cdma/dictionaries/tags/dictionaries-0.0.9/mappings/MamboSoleil/cdma_mambosoleil_config.xml
<?xml version="1.0" encoding="UTF8"?>
<!DOCTYPE plugin-config SYSTEM "../../dtd/plugin_config_file.dtd">
<plugin-config name="SOLEIL's Mambo plug-in configuration file">


<!-- ============================================
==  CONFIG 1: detection by file information    ==
============================================= -->
  <dataset-model name="fully_defined_conf">
    <plugin>
      <java>
        <set name="HDB_RAC" value="true"/>
        <set name="HDB_DRIVER" value="jdbc:oracle:thin"/>
        <set name="HDB_HOST" value="(DESCRIPTION = (ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS = (PROTOCOL = TCP)(HOST = calliope-vip.rcm) (PORT = 1521)) (ADDRESS = (PROTOCOL = TCP)(HOST = euterpe-vip.rcm)(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME = HDB)))"/>
        <set name="HDB_NAME" value="thalie:6200,euterpe:6200,calliope:6200"/>
        <set name="HDB_PORT" value="1521"/>
        <set name="HDB_SCHEMA" value="hdb"/>
        <!--
        <set name="HDB_USER" value=""/>
        <set name="HDB_PASSWORD" value=""/>
        -->
        <set name="TDB_RAC" value="true"/>
        <set name="TDB_DRIVER" value="jdbc:oracle:thin"/>
        <set name="TDB_HOST" value="(DESCRIPTION = (ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS = (PROTOCOL = TCP)(HOST = calliope-vip.rcm) (PORT = 1522)) (ADDRESS = (PROTOCOL = TCP)(HOST = euterpe-vip.rcm)(PORT = 1522))) (CONNECT_DATA = (SERVICE_NAME = TDB)))"/>
        <set name="TDB_NAME" value="thalie:6200,euterpe:6200,calliope:6200"/>
        <set name="TDB_PORT" value="1521"/>
        <set name="TDB_SCHEMA" value="tdb"/>
        <!--
        <set name="TDB_USER" value=""/>
        <set name="TDB_PASSWORD" value=""/>
        -->
      </java>
    </plugin>
  </dataset-model>
</plugin-config>

=== nhauser/cdma/dictionaries/trunk/SoleilNeXus/cdma_nexussoleil_config.xml
<?xml version="1.0" encoding="UTF8"?>
<!DOCTYPE plugin-config SYSTEM "../plugin_config_file.dtd">
<plugin-config name="SOLEIL's NeXus plug-in configuration file">
<!-- ============================================
==  CONFIG 1: detection by file information    ==
============================================= -->
  <dataset-model name="fully_defined_conf">
    <criteria>
      <if exist="true" target="/{NXentry}/{NXinstrument}"/>
      <if exist="true" target="/{NXentry}/acquisition_model"/>
    </criteria>

    <parameters> 
      <parameter name="BEAMLINE" type="name" target="/{NXentry}/{NXinstrument}"/>
      <parameter name="MODEL" type="value" target="/{NXentry}/acquisition_model"/>
    </parameters>

    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 2: all beamlines quickexafs         ==
============================================= -->
  <dataset-model name="generic_quickexafs">
    <criteria>
      <if exist="true" target="/QuickEXAFS*{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/{NXentry}/acquisition_model"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="name" target="/{NXentry}/{NXinstrument}"/>
      <parameter name="MODEL" type="constant" constant="quickexafs"/>
    </parameters>

    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 3: all beamlines scanserver         ==
============================================= -->
  <dataset-model name="generic_scanserver">
    <criteria>
      <if exist="true" target="/{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/QuickEXAFS*{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/{NXentry}/acquisition_model"/>
      <if exist="true" target="/{NXentry}/scan_data{NXdata}/time_1"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="name" target="/{NXentry}/{NXinstrument}"/>
      <parameter name="MODEL" type="constant" constant="scanserver"/>
    </parameters>

    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 5: all beamlines passerelle         ==
============================================= -->
  <dataset-model name="ANTARES_passerelle">
    <criteria>
      <if exist="true" target="/{NXentry}/ANTARES"/>
      <if exist="false" target="/{NXentry}/acquisition_model"/>
      <if exist="false" target="/{NXentry}/scan_data{NXdata}/time_1"/>
    </criteria>
<!-- 
    <parameters>
      <parameter name="BEAMLINE" type="constant" constant="antares"/>
      <parameter name="MODEL" type="constant" constant="passerelle" />
      </parameter>
    </parameters>
-->
    <plugin>
      <java>
        <set name="BEAMLINE" value="antares"/>
        <set name="MODEL" value="passerelle"/>
        <set name="fast_iterator" value="true"/>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 4: all beamlines flyscan            ==
============================================= -->
  <dataset-model name="generic_flyscan">
    <criteria>
      <if exist="true" target="/{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/QuickEXAFS*{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/{NXentry}/acquisition_model"/>
      <if exist="false" target="/{NXentry}/scan_data{NXdata}/time_1"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="name" target="/{NXentry}/{NXinstrument}"/>
      <parameter name="MODEL" type="constant" constant="flyscan"/>
    </parameters>
    
    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 5: all beamlines passerelle         ==
============================================= -->
  <dataset-model name="generic_passerelle">
    <criteria>
      <if exist="true" target="/{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/{NXentry}/ANTARES"/>
      <if exist="false" target="/QuickEXAFS*{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/{NXentry}/acquisition_model"/>
      <if exist="false" target="/{NXentry}/scan_data{NXdata}/time_1"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="name" target="/{NXentry}/{NXinstrument}"/>
      <parameter name="MODEL" type="constant" constant="passerelle"/>
    </parameters>

    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 5: test files                       ==
============================================= -->
  <dataset-model name="contacq_flyscan">
    <criteria>
      <if exist="true" target="/{NXentry}/contacq{NXinstrument}"/>
      <if exist="false" target="/QuickEXAFS*{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/{NXentry}/acquisition_model"/>
      <if exist="false" target="/{NXentry}/scan_data{NXdata}/time_1"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="constant" constant="contacq"/>
      <parameter name="MODEL" type="constant" constant="flyscan" />
    </parameters>
    
    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 6: test files                       ==
============================================= -->
  <dataset-model name="contacq_passerelle">
    <criteria>
      <if exist="false" target="/{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/QuickEXAFS*{NXentry}/{NXinstrument}"/>
      <if exist="false" target="/{NXentry}/acquisition_model"/>
      <if exist="true" target="/{NXentry}/scan_data{NXdata}/time_1"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="constant" constant="contacq"/>
      <parameter name="MODEL" type="constant" constant="passerelle"/>
    </parameters>
    
    <plugin>
      <java>
        <set name="log_debug" value="true" />
        <set name="N4T_buffer_size" value="300" />
        <set name="OPTIMAL_DATA_SIZE" value="3000000" />
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 5: test files                       ==
============================================= -->
  <dataset-model name="test_flyscan">
    <criteria>
      <if exist="false" target="/{NXentry}/{NXinstrument}"/>
      <if exist="true" target="/{NXentry}/scan_data{NXdata}/"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="constant" constant="contacq"/>
      <parameter name="MODEL" type="constant" constant="flyscan" />
    </parameters>
    
    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  Global section                             ==
============================================= -->
  <global>
    <java>
     <set name="CDMA_DEBUG" value="true"/>
    </java>
  </global>
</plugin-config>
